Khdoum.UI/Models/Notification.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Khdoum.UI.Models
{
    public class Notification:BaseModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="هذا الحقل مطلوب")]
        public string Title { get; set; }
        [Required(ErrorMessage = "هذا الحقل مطلوب")]
        public string Description { get; set; }
        public DateTime? DateAndTime { get; set; } = DateTime.Now;

        [Required(ErrorMessage = "هذا الحقل مطلوب")]
        public string[] Users { get; set; }
        public string SenderUser { get; set; } = "";

    }
}

Khdoum.UI/Controllers/NotificationsController.cs
using Khdoum.UI.Helpers;
using Khdoum.UI.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace Khdoum.UI.Controllers
{
    public class NotificationsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetList(string accessToken)
        {
            IEnumerable<Notification> Notifications = await NotificationsList(accessToken);
            return Json(new
            {
                Notifications = Notifications
            });
        }

        [HttpGet]
        public async Task<IActionResult> GetUsersListAjax(string Type)
        {
            IEnumerable<User> users = await UsersList(Type);
            return Json(new
            {
                users = users
            });
        }


        public async Task<IEnumerable<Notification>> NotificationsList(string accessToken)
        {
            IEnumerable<Notification> notifications = new List<Notification>();
            var Client = new HttpClient();
            var json = "";

            Client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(
                "Bearer", accessToken);


            HttpResponseMessage response = await Client.GetAsync($"{Constant.BaseAddress}api/Notifications/GetNotificationsForDashboardUser");
            if (response.IsSuccessStatusCode)
            {
                json = await response.Content.ReadAsStringAsync();
                notifications = JsonConvert.DeserializeObject<IEnumerable<Notification>>(json);
            }

            return notifications;
        }

        
        public async Task<IEnumerable<User>> UsersList(string Type)
        {
            IEnumerable<User> users = new List<User>();
            var Client = new HttpClient();
            var json = "";
            HttpResponseMessage response = await Client.GetAsync($"{Constant.BaseAddress}api/Users/{Type}");
            if (response.IsSuccessStatusCode)
            {
                json = await response.Content.ReadAsStringAsync();
                users = JsonConvert.DeserializeObject<IEnumerable<User>>(json);
            }

            return users;
        }


        [HttpPost]
        public async Task<IActionResult> Create(Notification notification)
        {
            if (ModelState.IsValid)
            {



                var Client = new HttpClient();

                var accessToken = notification.AccessToken;

                Client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(
                    "Bearer", accessToken);

                MultipartFormDataContent content = new MultipartFormDataContent();

                var users = notification.Users.Select(u => new UserNotification() { UserId = u });

                var UsersToJson = JsonConvert.SerializeObject(users);

                content.Add(new StringContent(notification.Title), "Title");
                content.Add(new StringContent(notification.Description), "Description");
                content.Add(new StringContent(notification.DateAndTime.ToString()), "DateAndTime");
                content.Add(new StringContent(notification.SenderUser), "SenderUser");
                //content.Add(new StringContent(UsersToJson), "Notifications");

                foreach(var item in notification.Users)
                {
                    content.Add(new StringContent(item.ToString()), $"Notifications[{Array.IndexOf(notification.Users,item)}].UserId");
                }



                var response = await Client.PostAsync(Constant.BaseAddress + "api/Notifications", content);
                if (response.IsSuccessStatusCode)
                {
                    return Json(new
                    {
                        Status = true
                    });
                }
            }

            return Json(new
            {
                Status = false
            });
        }

        

    }
}

Khdoum.UI/Views/Notifications/Index.cshtml
@model Khdoum.UI.Models.Notification
@{
    Layout = "DashboardLayout";
}

<h1>قائمة الاشعارات</h1>
<p>
    <a class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#AddModal">اضافة جديد</a>
</p>

<table class="table table-striped table-bordered text-center" id="table">
    <thead>
        <tr>
           
            <th>
                العنوان
            </th>
            <th>
                الوصف
            </th>
            <th>
                الوقت
            </th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="AddModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <form id="AddForm" method="post" asp-action="Create">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">اضافة</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Title" class="control-label">العنوان</label>
                                <input asp-for="Title" class="form-control Title" />
                                <span asp-validation-for="Title" class="text-danger "></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description" class="control-label">الرسالة</label>
                                <input asp-for="Description" class="form-control Description" />
                                <span asp-validation-for="Description" class="text-danger "></span>
                            </div>
                            <div class="form-group">
                                <label class="control-label">نوع المستخدمين</label>
                                <select class="form-control UserType">
                                    <option value="">اختر</option>
                                    <option value="User">عميل</option>
                                    <option value="Delegate">مندوب</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label asp-for="Users" class="control-label">المستخدمين</label>
                                <select name="Users" multiple class="form-control Users">
                                </select>
                                <span asp-validation-for="Users" class="text-danger "></span>
                            </div>



                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">اغلاق</button>
                    <button type="submit" id="AddBtn" class="btn btn-primary">اضافة</button>
                </div>
            </div>
        </form>

    </div>
</div>




@section Scripts
{
    <script>
        $(function () {


            FillTable();

            $("#AddForm").submit(function (e) {
                e.preventDefault();

                var isValid = $(this).valid();

                if (!isValid) {
                    return false;
                }

                Insert();
            });

        });

        function Insert() {

            //if (!Validation('#add_modal')) {
            //    e.preventDefault();
            //    return;
            //}

            //Create FormData object
            var fileData = new FormData();

            var SerializedData = $("#AddForm").serializeArray();





            $.each(SerializedData, function (index, item) {
                fileData.append(item.name, item.value);
            });


            var AccessToken = localStorage["accessToken"];
            fileData.append("AccessToken", AccessToken);




            $.ajax({
                type: 'POST',
                url: `@Url.Action("Create", "Notifications")`,
                processData: false,
                contentType: false,
                data: fileData ,
                //beforeSend: function () {

                //},

            success: function (data) {

                if (data.status == true) {
                    EmptyFeilds();
                    $('#AddModal').modal('hide');
                    FillTable();
                }


                //if (data.Message.Title != null && data.Message.Title != "" ) {
                //    var title = data.Message.Title;
                //    var body = data.Message.Description;
                //    var type = data.Message.Type;
                //    ShowMessage(title, body, type);
                //}
                },
                error: function (ex) {

                    console.log(ex);
                    console.log(response);

                    var r = jQuery.parseJSON(response.responseText);
                    alert("Message: " + r.Message);
                    alert("StackTrace: " + r.StackTrace);
                    alert("ExceptionType: " + r.ExceptionType);
                }
            });

        }

        function FillTable() {
            var Url = "@Url.Action("GetList", "Notifications")";

            var data = {
                accessToken: localStorage["accessToken"]
            }

            var Columns = [

                { data: 'title', 'title': 'العنوان' },
                { data: 'description', 'description': 'description' },
                { data: 'dateAndTime', 'dateAndTime': 'dateAndTime' }
            ];
            BuildAjaxDataTable($("#table"), Url, Columns, data,"notifications",false);
        }


        $(document).on("change", ".UserType", function () {
            var UserType = $(this).val();
            $(".Users option").remove();
            console.log(UserType);
            $.ajax({
                type: 'Get',
                url: `@Url.Action("GetUsersListAjax", "Notifications")`,
                //processData: false,
                //contentType: false,
                data: {
                    Type: UserType

                },
                //beforeSend: function () {

                //},

                success: function (data) {

                    $(".Users").prop("disabled", true);

                    var options = ``;

                    if (data.users.length > 0) {
                        $.each(data.users, function (index, item) {
                            options += `<option value="${item.id}">${item.name}</option>`;
                        });

                        $(".Users").append(options);

                        $(".Users").prop("disabled", false);

                    }

                },
                error: function (ex) {

                    console.log(ex);
                    console.log(response);

                    var r = jQuery.parseJSON(response.responseText);
                    alert("Message: " + r.Message);
                    alert("StackTrace: " + r.StackTrace);
                    alert("ExceptionType: " + r.ExceptionType);
                }
            });

        });

        $(document).on("change", ".Users", function () {
            if ($(this).val() == "all") {
                $('.Users option').prop('selected', true);
                $('.Users option:first').prop('selected', false);
            }
        });

    </script>
}